Hibernate
Aleksandr-K88org/Task-01 pull request #2
Opened 2023-11-20 21:20 UTC by Aleksandr-K88

2023-11-21 02:45 UTC, pdasilem requested changes

2023-11-21 02:45 UTC, pdasilem commented on src/main/java/jm/task/core/jdbc/dao/UserDaoHibernateImpl.java
> +        Session session = Util.getSessionFactory().openSession();
я не вижу здесь логики создания таблицы

2023-11-21 02:45 UTC, pdasilem commented on src/main/java/jm/task/core/jdbc/dao/UserDaoHibernateImpl.java
> +        } catch (Exception e) {
сузь эксепшн

2023-11-21 02:45 UTC, pdasilem commented on src/main/java/jm/task/core/jdbc/dao/UserDaoHibernateImpl.java
> +        Session session = Util.getSessionFactory().openSession();
здесь и везде - автозакрытие сессии и транзакции

2023-11-21 02:45 UTC, pdasilem commented on src/main/java/jm/task/core/jdbc/service/UserServiceImpl.java
> +    //    private UserDao userDao = new UserDaoJDBCImpl();
убрать закомментированный код

2023-11-21 02:45 UTC, pdasilem commented on src/main/java/jm/task/core/jdbc/util/Util.java
> +            throw new RuntimeException("Failed to initialize Hibernate", e);
зачем выбрасываешь исключение?

2023-12-24 22:35 UTC, Aleksandr-K88 commented
task1.1.4

2023-12-24 22:35 UTC, merged